src/LSV/Bundle/AppBundle/Entity/Classroom.php
<?php

namespace LSV\Bundle\AppBundle\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Criteria;
use Doctrine\ORM\Mapping as ORM;
use LSV\Bundle\AppBundle\Entity\ClassroomCouncil;
use LSV\Bundle\UserBundle\Entity\User;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="LSV\Bundle\AppBundle\Repository\ClassroomRepository")
 */
class Classroom
{
    /**
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @ORM\Column(type="string", length=50)
     * @Assert\NotBlank(
     *     groups = {"create", "edit"}
     * )
     * @Assert\Length(
     *     max = 50,
     *     groups = {"create", "edit"}
     * )
     */
    protected $label;

    /**
     * @ORM\Column(type="string", length=30)
     * @Assert\NotBlank(
     *     groups = {"create", "edit"}
     * )
     * @Assert\Length(
     *     max = 30,
     *     groups = {"create", "edit"}
     * )
     */
    protected $color;

    /**
     * @ORM\ManyToOne(targetEntity="LSV\Bundle\UserBundle\Entity\User", inversedBy="classrooms")
     */
    protected $user;

    /**
     * @ORM\OneToMany(targetEntity="Student", mappedBy="classroom", cascade={"ALL"})
     * @ORM\OrderBy({"lastname" = "ASC"})
     * @Assert\Valid
     */
    protected $students;

    /**
     * @ORM\OneToMany(targetEntity="LSV\Bundle\AppBundle\Entity\ClassroomCouncil", mappedBy="classroom", cascade={"ALL"})
     * @Assert\Valid
     */
    protected $classroomCouncils;

    /**
     * @ORM\OneToMany(targetEntity="LSV\Bundle\EventBundle\Entity\Lesson", mappedBy="classroom", cascade={"ALL"})
     * @Assert\Valid
     */
    protected $lessons;


    public function __construct() {
        $this->students = new ArrayCollection();
        $this->classroomCouncils = new ArrayCollection();
        $this->lessons = new ArrayCollection();
    }

    public function getId()
    {
        return $this->id;
    }

    public function setLabel($label)
    {
        $this->label = $label;
    }

    public function getLabel()
    {
        return $this->label;
    }

    public function setColor($color)
    {
        $this->color = $color;
    }

    public function getColor()
    {
        return $this->color;
    }

    public function setUser(User $user)
    {
        $this->user = $user;
    }

    public function getUser()
    {
        return $this->user;
    }

    public function addStudent(Student $student)
    {
        $student->setClassroom($this);
        return $this->students->add($student);
    }

    public function removeStudent(Student $student)
    {
        $student->setClassroom($this);
        return $this->students->removeElement($student);
    }

    public function getStudents()
    {
        return $this->students;
    }

    public function addClassroomCouncil(ClassroomCouncil $classroomCouncil)
    {
        $classroomCouncil->setClassroom($this);
        return $this->classroomCouncils->add($classroomCouncil);
    }

    public function removeClassroomCouncil(ClassroomCouncil $classroomCouncil)
    {
        $classroomCouncil->setClassroom($this);
        return $this->classroomCouncils->removeElement($classroomCouncil);
    }

    public function getClassroomCouncils()
    {
        return $this->classroomCouncils;
    }

    public function getLessons()
    {
        return $this->lessons;
    }

    public function getNextLessons() {
        $expr = Criteria::expr();
        $criteria = Criteria::create()
            ->where($expr->gte('startDatetime', new \Datetime('today')))
            ->orderBy(array('startDatetime' => Criteria::ASC))
            ->setMaxResults(4);
        return $this->lessons->matching($criteria);
    }

    public function getLessonIds()
    {
        return $this->lessons->map(function($entity) {
            return $entity->getId();
        })->toArray();
    }
}

src/LSV/Bundle/AppBundle/Entity/Student.php
<?php

namespace LSV\Bundle\AppBundle\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Criteria;
use Doctrine\ORM\Mapping as ORM;
use LSV\Bundle\AppBundle\Entity\StudentCouncil;
use LSV\Bundle\EventBundle\Entity\ExamResult;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="LSV\Bundle\AppBundle\Repository\StudentRepository")
 */
class Student
{
    /**
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @ORM\Column(type="string", length=100)
     * @Assert\NotBlank(
     *     groups = {"create", "edit"}
     * )
     * @Assert\Length(
     *     max = 100,
     *     groups = {"create", "edit"}
     * )
     */
    protected $lastname;

    /**
     * @ORM\Column(type="string", length=100)
     * @Assert\NotBlank(
     *     groups = {"create", "edit"}
     * )
     * @Assert\Length(
     *     max = 100,
     *     groups = {"create", "edit"}
     * )
     */
    protected $firstname;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    protected $birthdate = null;

    /**
     * @ORM\ManyToOne(targetEntity="Classroom", inversedBy="students")
     */
    protected $classroom;

    /**
     * @ORM\OneToMany(targetEntity="LSV\Bundle\EventBundle\Entity\ExamResult", mappedBy="student", cascade={"ALL"})
     * @Assert\Valid
     */
    protected $examResults;

    /**
     * @ORM\OneToMany(targetEntity="LSV\Bundle\AppBundle\Entity\StudentCouncil", mappedBy="student", cascade={"ALL"})
     * @Assert\Valid
     */
    protected $studentCouncils;

    /**
     * @ORM\OneToMany(targetEntity="LSV\Bundle\AppBundle\Entity\StudentSkill", mappedBy="student", cascade={"ALL"})
     * @Assert\Valid
     */
    protected $studentSkills;


    public function __construct() {
        $this->examResults = new ArrayCollection();
        $this->studentCouncils = new ArrayCollection();
        $this->studentSkills = new ArrayCollection();
    }

    public function getId()
    {
        return $this->id;
    }

    public function setLastname($lastname)
    {
        $this->lastname = $lastname;
    }

    public function getLastname()
    {
        return $this->lastname;
    }

    public function setFirstname($firstname)
    {
        $this->firstname = $firstname;
    }

    public function getFirstname()
    {
        return $this->firstname;
    }

    public function getFullname()
    {
        return $this->firstname.' '.$this->lastname;
    }

    public function setBirthdate(\Datetime $birthdate = null)
    {
        $this->birthdate = $birthdate;
    }

    public function getBirthdate()
    {
        return $this->birthdate;
    }

    public function getBirth()
    {
        if ($this->birthdate) {
            $dateNow = new \DateTime("now");
            $interval = $dateNow->diff($this->birthdate);
            ;
            return $this->birthdate->format('d/m/Y').' ('.$interval->format('%y ans').')';
        }
        return $this->birthdate;
    }

    public function setClassroom(Classroom $classroom)
    {
        $this->classroom = $classroom;
    }

    public function getClassroom()
    {
        return $this->classroom;
    }

    public function addExamResult(ExamResult $examResult)
    {
        $examResult->setStudent($this);
        return $this->examResults->add($examResult);
    }

    public function removeExamResult(ExamResult $examResult)
    {
        $examResult->setStudent($this);
        return $this->examResults->removeElement($examResult);
    }

    public function getExamResults()
    {
        return $this->examResults;
    }

    public function addStudentCouncil(StudentCouncil $studentCouncil)
    {
        $studentCouncil->setStudent($this);
        return $this->studentCouncils->add($studentCouncil);
    }

    public function removeStudentCouncil(StudentCouncil $studentCouncil)
    {
        $studentCouncil->setStudent($this);
        return $this->studentCouncils->removeElement($studentCouncil);
    }

    public function getStudentCouncils()
    {
        return $this->studentCouncils;
    }

    public function addStudentSkill(StudentSkill $studentSkill)
    {
        $studentSkill->setStudent($this);
        return $this->studentSkills->add($studentSkill);
    }

    public function removeStudentSkill(StudentSkill $studentSkill)
    {
        $studentSkill->setStudent($this);
        return $this->studentSkills->removeElement($studentSkill);
    }

    public function getStudentSkills()
    {
        return $this->studentSkills;
    }

    public function getUsedTrimesters()
    {
        $usedTrimester = new ArrayCollection();

        $criteria = Criteria::create()
          ->orderBy(array("label" => Criteria::DESC));

        foreach ($this->examResults as $key => $examResult) {
            $trimester = $examResult->getExam()->getTrimester();
            if (!$usedTrimester->contains($trimester)) {
                $usedTrimester->add($trimester);
            }
        }

        return $usedTrimester->matching($criteria);
    }

    public function getAverage()
    {
        $average = 0;
        $nullMark = 0;
        $i = 0;
        foreach ($this->getExamResults() as $result) {
            $mark = $result->getMark();
            $coef = $result->getExam()->getCoefficient();

            // If there is a mark
            if (null !== $mark) {
                $average += ($mark * $coef);
            }
            else { // If no mark
                $nullMark += $coef;
            }
            $i += $coef;
        }

        $i = ($i - $nullMark);

        return ($i > 0) ? round($average / $i, 2).' / 20' : 'Pas de notes';
    }
}

src/LSV/Bundle/AppBundle/Controller/ClassroomController.php
<?php

namespace LSV\Bundle\AppBundle\Controller;

use LSV\Bundle\AppBundle\Entity\Classroom;
use LSV\Bundle\AppBundle\Entity\ClassroomCouncil;
use LSV\Bundle\AppBundle\Entity\StudentCouncil;
use LSV\Bundle\AppBundle\Entity\StudentSkill;
use LSV\Bundle\AppBundle\Form\Type\ClassroomType;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;

class ClassroomController extends Controller
{
    public function indexAction($active)
    {
        $em = $this->getDoctrine()->getManager();
        $classrooms = $em->getRepository('LSVAppBundle:Classroom')
            ->findByUser($this->getUser())
        ;

        return $this->render('LSVAppBundle:Classroom:index.html.twig', array(
            'classrooms' => $classrooms,
            '_active' => $active,
        ));
    }

    public function showAction(Classroom $classroom)
    {
        $usr = $classroom->getUser();
        if ($this->getUser() !== $usr) {
            throw $this->createAccessDeniedException();
        }

        $em = $this->getDoctrine()->getManager();

        $lastExams = $em->getRepository('LSVEventBundle:Exam')->lastExams(
            $classroom->getLessonIds()
        );

        $deleteForm = $this->createDeleteForm($classroom);

        return $this->render('LSVAppBundle:Classroom:show.html.twig', array(
            'classroom' => $classroom,
            'last_exams' => $lastExams,
            'delete_form' => $deleteForm->createView(),
        ));
    }

    public function createAction(Request $request)
    {
        $classroom = new Classroom();

        $form = $this->createForm(ClassroomType::class, $classroom, array(
            'validation_groups' => array('create'),
        ));
        $formType = 'create';

        if ('POST' === $request->getMethod()) {
            $form->handleRequest($request);

            if ($form->isSubmitted() && $form->isValid()) {
                $em = $this->getDoctrine()->getManager();

                $trimesters = $em->getRepository('LSVEventBundle:Trimester')->findAll();
                $skills = $em->getRepository('LSVAppBundle:Skill')->findAll();
                $students = $classroom->getStudents();
                foreach ($trimesters as $trimester) {
                    $classroom->addClassroomCouncil(ClassroomCouncil::withClassroomTrimester(
                        $classroom,
                        $trimester
                    ));

                    foreach ($students as $student) {
                        $student->addStudentCouncil(StudentCouncil::withStudentTrimester(
                            $student,
                            $trimester
                        ));
                        foreach ($skills as $skill) {
                            $student->addStudentSkill(StudentSkill::withStudentTrimester(
                                $student,
                                $trimester,
                                $skill
                            ));
                        }
                    }
                }

                $classroom->setUser($this->getUser());

                $em->persist($classroom);
                $em->flush();

                $this->addFlash(
                    'success',
                    'La classe a été enregistrée avec succès.'
                );

                return $this->redirectToRoute('classroom_show', array(
                    'id' => $classroom->getId()
                ));
            }
        }

        return $this->render('LSVAppBundle:Classroom:edit.html.twig', array(
            'form' => $form->createView(),
            'form_type' => $formType,
        ));
    }

    public function editAction(Request $request, Classroom $classroom)
    {
        $usr = $classroom->getUser();
        if ($this->getUser() !== $usr) {
            throw $this->createAccessDeniedException();
        }

        $old_students = $classroom->getStudents();

        $formType = 'edit';
        $form = $this->createForm(ClassroomType::class, $classroom, array(
            'validation_groups' => array($formType),
        ));

        if ('POST' === $request->getMethod()) {
            $form->handleRequest($request);

            if ($form->isSubmitted() && $form->isValid()) {
                $em = $this->getDoctrine()->getManager();

                $trimesters = $em->getRepository('LSVEventBundle:Trimester')->findAll();
                $classroomCouncils = $classroom->getClassroomCouncils();
                $students = $classroom->getStudents();
                foreach ($trimesters as $trimester) {
                    foreach ($students as $student) {
                        if (!$old_students->contains($student)) {
                            $student->addStudentCouncil(StudentCouncil::withStudentTrimester(
                                $student,
                                $trimester
                            ));
                            foreach ($skills as $skill) {
                                $student->addStudentSkill(StudentSkill::withStudentTrimester(
                                    $student,
                                    $trimester,
                                    $skill
                                ));
                            }
                        }
                    }
                }

                $em->persist($classroom);
                $em->flush();

                $this->addFlash(
                    'success',
                    'La classe a été modifiée avec succès.'
                );

                return $this->redirectToRoute('classroom_show', array(
                    'id' => $classroom->getId()
                ));
            }
        }

        return $this->render('LSVAppBundle:Classroom:edit.html.twig', array(
            'classroom' => $classroom,
            'form' => $form->createView(),
            'form_type' => $formType,
        ));
    }

    public function deleteAction(Request $request, $id)
    {
        $em = $this->getDoctrine()->getManager();
        $classroom = $em->getRepository('LSVAppBundle:Classroom')
            ->findOneById($id)
        ;

        if (!$classroom) {
            $this->addFlash(
                'danger',
                sprintf(
                    'La classe n° %d n\'a pas été trouvée',
                    $id
                )
            );
            return $this->redirectToRoute('event_index');
        }

        $usr = $classroom->getUser();
        if ($this->getUser() !== $usr) {
            throw $this->createAccessDeniedException();
        }

        $form = $this->createDeleteForm($classroom);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $em->remove($classroom);
            $em->flush();

            $this->addFlash(
                'success',
                'La classe a été supprimée avec succès.'
            );
        }
        else {
            $this->addFlash(
                'danger',
                'La classe n\'a pas été supprimée.'
            );
        }

        return $this->redirectToRoute('event_index');
    }

    private function createDeleteForm(Classroom $classroom)
    {

        return $this->createFormBuilder()
            ->setAction($this->generateUrl('classroom_delete', array(
                'id' => $classroom->getId()
            )))
            ->setMethod('DELETE')
            ->getForm()
        ;
    }
}

src/LSV/Bundle/AppBundle/Resources/views/Classroom/index.html.twig
{% set active = _active %}

<ul class="treeview-menu">
    {% for classroom in classrooms %}
        <li class="{{ active == 'classroom_' ~ classroom.id ? 'active' }}">
            <a href="{{ path('classroom_show', { 'id': classroom.id }) }}">
                <small style="color:{{ classroom.color }};">
                    <i class="fa fa-square"></i>
                </small>
                {{ classroom.label }}
            </a>
        </li>
    {% else %}
        <li>
            <a href="{{ path('classroom_create') }}">
                <i class="fa fa-graduation-cap"></i>
                <span>Créer une classe</span>
            </a>
        </li>
    {% endfor %}
</ul>

src/LSV/Bundle/AppBundle/Resources/views/Classroom/show.html.twig
{% extends 'base.html.twig' %}

{% trans_default_domain 'LSVAppBundle' %}

{% set active_parent = 'classroom' %}
{% set active = 'classroom_' ~ classroom.id %}

{% block title %}
    {{ classroom.label }} -
{% endblock %}

{% block stylesheets %}
<style type="text/css">
    .sub-footer {
        border-top: 1px solid #E0E0E0;
        padding: 10px;
    }
    .nowrap {
        white-space: nowrap;
    }
    .btn-edit {
        display: none;
    }
    .hovering {
        background: #f5f5f5;
    }
    td.disabled {
        color: #999999;
    }
</style>
{% endblock %}

{% block page_title %}
    <i class="fa fa-graduation-cap"></i>
    {{ classroom.label }}
    <small>
        <span style="color:{{ classroom.color }};">
            <i class="fa fa-square"></i>
        </span>
    </small>
{% endblock %}

{% block content %}
    <div class="col-md-4">
        <div id="list-student" class="box box-default" style="border-color: #141f34">
            <div class="box-header with-border">
                <i class="fa fa-users"></i>
                <h3 class="box-title">{{ 'label.students'|trans }}</h3>
                <small>({{ classroom.students|length }})</small>
            </div>
            <div class="box-body">
                <div class="input-group input-group-sm">
                    <input class="form-control search" type="text" placeholder="Search ...">
                    <span class="input-group-btn">
                        <button type="button" class="btn btn-default">
                            <i class="fa fa-search"></i>
                        </button>
                    </span>
                </div>
                <br>
                <ul class="list list-group list-group-unbordered">
                    {% for student in classroom.students %}
                        <li class="list-group-item">
                            <a class="btn btn-default btn-xs pull-right" href="{{ path('student_show', {'id': student.id}) }}">
                                <i class="fa fa-user"></i>
                            </a>
                            <a href="{{ path('student_show', {'id': student.id}) }}">
                                <span class="name">{{ student.fullname }}</span>
                            </a>
                        </li>
                    {% else %}
                        <div class="callout callout-warning">
                            <strong>
                                <i class="fa fa-exclamation-triangle"></i> {{ 'msg.warning.title'|trans }}
                            </strong>
                            {{ 'msg.noResultFound'|trans }}
                        </div>
                    {% endfor %}
                </ul>
            </div>
            <div class="box-footer">
                <ul class="pagination pagination-sm" style="margin: 0px;"></ul>
            </div>

        </div>
    </div>
    <div class="col-md-8">
        <div class="box" style="border-color: #50637f">
            <div class="box-header with-border">
                <i class="fa fa-list"></i>
                <h3 class="box-title">{{ 'label.last_exams'|trans }}</h3>
            </div>
            <div class="box-body">
                <ul class="list-group list-group-unbordered">
                    {% for exam in last_exams %}
                        <li class="list-group-item">
                            <small>
                                <strong>{{ exam.trimester.shortLabel }}</strong>
                            </small>
                            <a class="btn btn-default btn-xs pull-right" href="{{ path('exam_show', {'id': exam.id}) }}">
                                <i class="fa fa-external-link-square"></i>
                            </a> -
                            Le {{ exam.lesson.startDatetime|date('d/m/Y') }} -
                            <a href="{{ path('exam_show', {'id': exam.id}) }}">
                                {{ exam.title }}
                            </a>
                        </li>
                    {% else %}
                        <div class="callout callout-warning">
                            <strong>
                                <i class="fa fa-exclamation-triangle"></i> {{ 'msg.warning.title'|trans }}
                            </strong>
                            {{ 'msg.noResultFound'|trans }}
                        </div>
                    {% endfor %}
                </ul>
            </div>
        </div>
        <div class="box" style="border-color: #d5b388">
            <div class="box-header with-border">
                <i class="fa fa-list"></i>
                <h3 class="box-title">{{ 'label.nextLessons'|trans }}</h3>
            </div>
            <div class="box-body">
                <ul class="list-group list-group-unbordered">
                    {% for lesson in classroom.nextLessons %}
                        <li class="list-group-item">
                            <a class="btn btn-default btn-xs pull-right" href="{{ path('lesson_show', {'id': lesson.id}) }}">
                                <i class="fa fa-external-link-square"></i>
                            </a> -
                            Le {{ lesson.startDatetime|date('d/m/Y H:i') }} -
                            <a href="{{ path('lesson_show', {'id': lesson.id}) }}">
                                {{ lesson.title }}
                            </a>
                        </li>
                    {% else %}
                        <div class="callout callout-warning">
                            <strong>
                                <i class="fa fa-exclamation-triangle"></i> {{ 'msg.warning.title'|trans }}
                            </strong>
                            {{ 'msg.noResultFound'|trans }}
                        </div>
                    {% endfor %}
                </ul>
            </div>
        </div>
        <div class="box" style="border-color: #b28039">
            <div class="box-header with-border">
                <i class="fa fa-list-alt"></i>
                <h3 class="box-title">{{ 'label.councils'|trans }}</h3>
            </div>
            <div class="box-body">
                <table class="table table-bordered table-council">
                    {% for classroomCouncil in classroom.classroomCouncils %}
                        <tr class="fullrow row{{ loop.index }}" data-id="{{ loop.index }}">
                            <th class="col-md-2 nowrap" rowspan="2">
                                {{ classroomCouncil.trimester.label }}<br>
                                <a class="btn btn-primary btn-xs btn-edit" href="{{ path('council_edit', { 'type': 'classroom', 'id': classroomCouncil.classroom.id, 'trimester_id': classroomCouncil.trimester.id }) }}">
                                    Éditer la classe
                                </a><br>
                                <a class="btn btn-primary btn-xs btn-edit" href="{{ path('council_students_edit', { 'classroom_id': classroomCouncil.classroom.id, 'trimester_id': classroomCouncil.trimester.id }) }}">
                                    Éditer les étudiants
                                </a>
                            </th>
                            <td class="col-md-8 {{ (classroomCouncil.council.advice is null) ? 'disabled' }}">
                                {{ classroomCouncil.council.advice|default('default.noAdvice'|trans) }}
                            </td>
                            <td class="col-md-2">
                                <strong>{{ 'default.advice'|trans }}</strong>
                            </td>
                        </tr>
                        <tr class="fullrow row{{ loop.index }}" data-id="{{ loop.index }}">
                            <td class="{{ (classroomCouncil.council.userAdvice is null) ? 'disabled' }}">
                                {{ classroomCouncil.council.userAdvice|default('default.noUserAdvice'|trans) }}
                            </td>
                            <td>
                                <strong>{{ 'default.userAdvice'|trans }}</strong>
                            </td>
                        </tr>
                    {% else %}
                        <div class="callout callout-warning">
                            <strong>
                                <i class="fa fa-exclamation-triangle"></i> {{ 'msg.warning.title'|trans }}
                            </strong>
                            {{ 'msg.noResultFound'|trans }}
                        </div>
                    {% endfor %}
                </table>
            </div>
        </div>
    </div>
    <div class="col-md-12">
        <div class="col-md-12 sub-footer">
            {{ form_start(delete_form) }}
                <button class="btn-link text-red" onclick="return confirm('{{ 'label.delete.confirm_classroom'|trans }}')" type="submit">
                    {{ 'label.delete.classroom'|trans }}
                </button>
                <a class="text-primary" href="{{ path('classroom_edit', { 'id': classroom.id }) }}">
                    {{ 'label.edit.classroom'|trans }}
                </a>
            {{ form_end(delete_form) }}
        </div>
    </div>
{% endblock %}

{% block javascripts %}
    <script src="http://listjs.com/assets/javascripts/list.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/list.pagination.js/0.1.1/list.pagination.min.js"></script>

    <script type="text/javascript">
        var monkeyList = new List('list-student', {
            valueNames: ['name'],
            page: 12,
            plugins: [ ListPagination({
                innerWindow: 0,
                outerWindow: 0,
                left: 1,
                right: 1,
            }) ]
        });
        $(".fullrow").hover(function() {
            var id = this.getAttribute("data-id");
            $(".row" + id).addClass("hovering");
            $(this).find(".btn-edit").show();
        }).on("blur mouseleave", function() {
            var id = this.getAttribute("data-id");
            $(".row" + id).removeClass("hovering");
            $(".btn-edit").hide();
        });
    </script>
{% endblock %}