src/LSV/Bundle/AppBundle/Entity/Student.php
<?php

namespace LSV\Bundle\AppBundle\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Criteria;
use Doctrine\ORM\Mapping as ORM;
use LSV\Bundle\AppBundle\Entity\StudentCouncil;
use LSV\Bundle\EventBundle\Entity\ExamResult;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="LSV\Bundle\AppBundle\Repository\StudentRepository")
 */
class Student
{
    /**
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @ORM\Column(type="string", length=100)
     * @Assert\NotBlank(
     *     groups = {"create", "edit"}
     * )
     * @Assert\Length(
     *     max = 100,
     *     groups = {"create", "edit"}
     * )
     */
    protected $lastname;

    /**
     * @ORM\Column(type="string", length=100)
     * @Assert\NotBlank(
     *     groups = {"create", "edit"}
     * )
     * @Assert\Length(
     *     max = 100,
     *     groups = {"create", "edit"}
     * )
     */
    protected $firstname;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    protected $birthdate = null;

    /**
     * @ORM\ManyToOne(targetEntity="Classroom", inversedBy="students")
     */
    protected $classroom;

    /**
     * @ORM\OneToMany(targetEntity="LSV\Bundle\EventBundle\Entity\ExamResult", mappedBy="student", cascade={"ALL"})
     * @Assert\Valid
     */
    protected $examResults;

    /**
     * @ORM\OneToMany(targetEntity="LSV\Bundle\AppBundle\Entity\StudentCouncil", mappedBy="student", cascade={"ALL"})
     * @Assert\Valid
     */
    protected $studentCouncils;

    /**
     * @ORM\OneToMany(targetEntity="LSV\Bundle\AppBundle\Entity\StudentSkill", mappedBy="student", cascade={"ALL"})
     * @Assert\Valid
     */
    protected $studentSkills;


    public function __construct() {
        $this->examResults = new ArrayCollection();
        $this->studentCouncils = new ArrayCollection();
        $this->studentSkills = new ArrayCollection();
    }

    public function getId()
    {
        return $this->id;
    }

    public function setLastname($lastname)
    {
        $this->lastname = $lastname;
    }

    public function getLastname()
    {
        return $this->lastname;
    }

    public function setFirstname($firstname)
    {
        $this->firstname = $firstname;
    }

    public function getFirstname()
    {
        return $this->firstname;
    }

    public function getFullname()
    {
        return $this->firstname.' '.$this->lastname;
    }

    public function setBirthdate(\Datetime $birthdate = null)
    {
        $this->birthdate = $birthdate;
    }

    public function getBirthdate()
    {
        return $this->birthdate;
    }

    public function getBirth()
    {
        if ($this->birthdate) {
            $dateNow = new \DateTime("now");
            $interval = $dateNow->diff($this->birthdate);
            ;
            return $this->birthdate->format('d/m/Y').' ('.$interval->format('%y ans').')';
        }
        return $this->birthdate;
    }

    public function setClassroom(Classroom $classroom)
    {
        $this->classroom = $classroom;
    }

    public function getClassroom()
    {
        return $this->classroom;
    }

    public function addExamResult(ExamResult $examResult)
    {
        $examResult->setStudent($this);
        return $this->examResults->add($examResult);
    }

    public function removeExamResult(ExamResult $examResult)
    {
        $examResult->setStudent($this);
        return $this->examResults->removeElement($examResult);
    }

    public function getExamResults()
    {
        return $this->examResults;
    }

    public function addStudentCouncil(StudentCouncil $studentCouncil)
    {
        $studentCouncil->setStudent($this);
        return $this->studentCouncils->add($studentCouncil);
    }

    public function removeStudentCouncil(StudentCouncil $studentCouncil)
    {
        $studentCouncil->setStudent($this);
        return $this->studentCouncils->removeElement($studentCouncil);
    }

    public function getStudentCouncils()
    {
        return $this->studentCouncils;
    }

    public function addStudentSkill(StudentSkill $studentSkill)
    {
        $studentSkill->setStudent($this);
        return $this->studentSkills->add($studentSkill);
    }

    public function removeStudentSkill(StudentSkill $studentSkill)
    {
        $studentSkill->setStudent($this);
        return $this->studentSkills->removeElement($studentSkill);
    }

    public function getStudentSkills()
    {
        return $this->studentSkills;
    }

    public function getUsedTrimesters()
    {
        $usedTrimester = new ArrayCollection();

        $criteria = Criteria::create()
          ->orderBy(array("label" => Criteria::DESC));

        foreach ($this->examResults as $key => $examResult) {
            $trimester = $examResult->getExam()->getTrimester();
            if (!$usedTrimester->contains($trimester)) {
                $usedTrimester->add($trimester);
            }
        }

        return $usedTrimester->matching($criteria);
    }

    public function getAverage()
    {
        $average = 0;
        $nullMark = 0;
        $i = 0;
        foreach ($this->getExamResults() as $result) {
            $mark = $result->getMark();
            $coef = $result->getExam()->getCoefficient();

            // If there is a mark
            if (null !== $mark) {
                $average += ($mark * $coef);
            }
            else { // If no mark
                $nullMark += $coef;
            }
            $i += $coef;
        }

        $i = ($i - $nullMark);

        return ($i > 0) ? round($average / $i, 2).' / 20' : 'Pas de notes';
    }
}

src/LSV/Bundle/AppBundle/Form/Type/StudentType.php
<?php

namespace LSV\Bundle\AppBundle\Form\Type;

use LSV\Bundle\AppBundle\Entity\Student;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class StudentType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('lastname', Type\TextType::class, array(
                'label' => 'form.student.lastname',
                'attr' => array(
                    'placeholder' => 'form.student.lastname'
                ),
            ))
            ->add('firstname', Type\TextType::class, array(
                'label' => 'form.student.firstname',
                'attr' => array(
                    'placeholder' => 'form.student.firstname'
                ),
            ))
            ->add('birthdate', Type\BirthdayType::class, array(
                'label' => 'form.student.birthdate.label',
                'required' => false,
                'placeholder' => array(
                    'year' => 'form.student.birthdate.year',
                    'month' => 'form.student.birthdate.month',
                    'day' => 'form.student.birthdate.day',
                ),
                'years' => range(date('Y'), date('Y') - 40),
            ))
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => Student::class,
            'translation_domain' => 'LSVAppBundle',
        ));
    }

    public function getBlockPrefix()
    {
        return 'app_student';
    }
}

src/LSV/Bundle/AppBundle/Controller/StudentController.php
<?php

namespace LSV\Bundle\AppBundle\Controller;

use LSV\Bundle\AppBundle\Entity\Student;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;

class StudentController extends Controller
{
    public function showAction($id)
    {
        $em = $this->getDoctrine()->getManager();
        $student = $em->getRepository('LSVAppBundle:Student')
            ->findOneById($id)
        ;

        if (!$student) {
            throw $this->createNotFoundException(sprintf(
                'L\'étudiant %d n\'a pas été trouvé',
                $id
            ));
        }

        $usr = $student->getClassroom()->getUser();
        if ($this->getUser() !== $usr) {
            throw $this->createAccessDeniedException();
        }

        $adj_student = $em->getRepository('LSVAppBundle:Student')
            ->getAdjacentsStudent($student)
        ;

        $deleteForm = $this->createDeleteForm($student);

        return $this->render('LSVAppBundle:Student:show.html.twig', array(
            'delete_form' => $deleteForm->createView(),
            'student' => $student,
            'adj_student' => $adj_student,
        ));
    }

    public function deleteAction(Request $request, $id)
    {
        $em = $this->getDoctrine()->getManager();
        $student = $em->getRepository('LSVAppBundle:Student')
            ->findOneById($id)
        ;

        if (!$student) {
            $this->addFlash(
                'danger',
                sprintf(
                    'L\'étudiant n° %d n\'a pas été trouvé',
                    $id
                )
            );
            return $this->redirectToRoute('classroom_show', array(
                'id' => $classroom->getId(),
            ));
        }

        $usr = $student->getClassroom()->getUser();
        if ($this->getUser() !== $usr) {
            throw $this->createAccessDeniedException();
        }

        $form = $this->createDeleteForm($student);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $classroom = $student->getClassroom();

            $em->remove($student);
            $em->flush();

            $this->addFlash(
                'success',
                'L\'étudiant a été supprimé avec succès.'
            );
        }
        else {
            $this->addFlash(
                'danger',
                'L\'étudiant n\'a pas été supprimé.'
            );
        }

        return $this->redirectToRoute('classroom_show', array(
            'id' => $classroom->getId(),
        ));
    }

    private function createDeleteForm(Student $student)
    {

        return $this->createFormBuilder()
            ->setAction($this->generateUrl('student_delete', array(
                'id' => $student->getId()
            )))
            ->setMethod('DELETE')
            ->getForm()
        ;
    }
}

src/LSV/Bundle/AppBundle/Resources/views/Student/index.html.twig
{% extends 'base.html.twig' %}

{% trans_default_domain 'LSVAppBundle' %}

{% set active_parent = 'student' %}
{% set active = 'student_index' %}

{% block page_title %}Administration{% endblock %}
{% block content %}
    <div class="col-xs-12">
        <div class="box">
            <div class="box-header">
                <h3 class="box-title">Liste des classes</h3>
            </div>
            <!-- /.box-header -->
            <div class="box-body">
                <table class="table table-bordered table-hover">
                    <thead>
                        <tr>
                            <th>Libelle</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for classroom in classrooms %}
                            <tr>
                                <td>
                                    <a href="{{ path('classroom_show', { 'id': classroom.id }) }}">
                                        {{ classroom.label }}
                                    </a>
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>

            </div>
            <!-- /.box-body -->
        </div>
        <!-- /.box -->
    </div>
    <!-- /.col -->
{% endblock %}

src/LSV/Bundle/AppBundle/Resources/views/Student/show.html.twig
{% extends 'base.html.twig' %}

{% trans_default_domain 'LSVAppBundle' %}

{% set active_parent = 'classroom' %}
{% set active = 'classroom_' ~ student.classroom.id %}

{% block title %}
    {{ student.fullname }} - {{ student.classroom.label }} -
{% endblock %}

{% block stylesheets %}
    <style type="text/css">
        .label {
            font-size: 0.85em;
        }
        .sub-footer {
            border-top: 1px solid #E0E0E0;
            padding: 10px;
        }
        td.disabled {
            color: #999999;
        }
    </style>
{% endblock stylesheets %}

{% block content %}
    <div class="box box-solid">
        <div class="box-header with-border text-center">
            <div class="col-xs-4">
                {% if adj_student.prev %}
                    <a class="btn btn-link" href="{{ path('student_show', {'id': adj_student.prev.id}) }}">
                        <i class="fa fa-chevron-left"></i> {{ adj_student.prev.fullname }}
                    </a>
                {% endif %}
            </div>
            <div class="col-xs-4">
                <a class="btn btn-link" href="{{ path('classroom_show', { 'id': student.classroom.id }) }}">
                    <i class="fa fa-chevron-up"></i> {{ student.classroom.label }} <i class="fa fa-chevron-up"></i>
                </a>
            </div>
            <div class="col-xs-4">
                {% if adj_student.next %}
                    <a class="btn btn-link" href="{{ path('student_show', {'id': adj_student.next.id}) }}">
                        {{ adj_student.next.fullname }} <i class="fa fa-chevron-right"></i>
                    </a>
                {% endif %}
            </div>
        </div>
        <div class="box-header with-border">
            <h3 class="box-title" style="padding: 0px;font-size: 2em;">
                {{ student.fullname }}
                <small>{{ student.birth }}</small>
            </h3>
        </div>
        <div class="box-body">
            <div class="col-md-12">
                <p>
                    <span class="label label-default">{{ 'label.yearAverage'|trans }} : {{ student.average }}</span>
                </p>
            </div>
            <div class="col-md-12">
                {% for trimester in student.usedTrimesters %}
                    <div class="box box-primary box-solid">
                        <div class="box-header with-border">
                            <h3 class="box-title">{{ trimester.label }}</h3>
                        </div>
                        <!-- /.box-header -->
                        <div class="box-body">
                            {% for studentCouncil in trimester.studentCouncils if studentCouncil.student == student and studentCouncil.trimester == trimester %}
                                <div class="col-md-12 ">
                                    <div class="well well-lg">
                                        <p>
                                            {{ 'label.average'|trans }} :
                                            <span class="label label-info">
                                                {{ studentCouncil.average }}
                                            </span>
                                        </p>
                                        <div class="col-md-6">
                                            <blockquote>
                                                <p>{{ 'label.advice'|trans }}</p>
                                                <small>{{ studentCouncil.council.advice|default('default.noAdvice'|trans) }}</small>
                                            </blockquote>
                                        </div>
                                        <div class="col-md-6">
                                            <blockquote>
                                                <p>{{ 'label.userAdvice'|trans }}</p>
                                                <small>{{ studentCouncil.council.userAdvice|default('default.noUserAdvice'|trans) }}</small>
                                            </blockquote>
                                        </div>
                                        <a href="{{ path('council_edit', { 'type': 'student', 'id': studentCouncil.student.id, 'trimester_id': studentCouncil.trimester.id }) }}" class="btn btn-primary btn-xs text-right">
                                            Editer
                                        </a>
                                    </div>
                                </div>
                            {% endfor %}
                            <div class="col-md-8">
                                <div class="box box-warning">
                                    <div class="box-header with-border">
                                        <h3 class="box-title">
                                            Notes
                                        </h3>
                                    </div>
                                    <div class="box-body" style="height: 100%;">

                                        <div class="row">
                                            <div class="col-md-12">
                                                {% for result in student.examResults %}
                                                    {% if loop.first %}
                                                        <table class="table table-striped">
                                                            <thead>
                                                                <tr>
                                                                    <th>Date</th>
                                                                    <th>Contrôle</th>
                                                                    <th>Note</th>
                                                                    <th>Commentaire</th>
                                                                </tr>
                                                            </thead>
                                                            <tbody>
                                                    {% endif %}
                                                    {% if result.exam.trimester == trimester %}
                                                        <tr>
                                                            <td>
                                                                {{ result.exam.lesson.startDatetime|date('d/m/Y') }}
                                                            </td>
                                                            <td>
                                                                <a href="{{ path('exam_show', { 'id': result.exam.id }) }}">
                                                                    {{ result.exam.title }}
                                                                </a>
                                                            </td>
                                                            <td class="{{ (result.mark is null) ? 'disabled' }}">
                                                                {{ result.mark|default('Pas de note') }}
                                                            </td>
                                                            <td class="{{ (result.comment is null) ? 'disabled' }}">
                                                                {{ result.comment|default('Pas de commentaire') }}
                                                            </td>
                                                            <td>
                                                                <a href="{{ path('exam_show', { 'id': result.exam.id }) }}" class="btn btn-default btn-xs pull-right">
                                                                    <i class="fa fa-external-link-square"></i>
                                                                </a>
                                                            </td>
                                                        </tr>
                                                    {% endif %}
                                                    {% if loop.last %}
                                                            </tbody>
                                                        </table>
                                                    {% endif %}
                                                {% else %}
                                                    <div class="callout callout-warning">
                                                        <strong>
                                                            <i class="fa fa-exclamation-triangle"></i> {{ 'msg.warning.title'|trans }}
                                                        </strong>
                                                        {{ 'msg.noResultFound'|trans }}
                                                    </div>
                                                {% endfor %}
                                            </div>

                                        </div>

                                    </div>
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="box box-danger">
                                    <div class="box-header with-border">
                                        <h3 class="box-title">
                                            Compétences
                                        </h3>
                                        <div class="pull-right box-tools">
                                            <a class="btn btn-default btn-sm" href="{{ path('skill_edit', { 'student_id': student.id, 'trimester_id': trimester.id }) }}">
                                                <i class="fa fa-edit"></i>
                                            </a>
                                        </div>
                                    </div>
                                    <div class="box-body">
                                        {% for studentSkill in student.studentSkills if studentSkill.trimester == trimester %}
                                            <div class="col-md-12">
                                                <label>{{ studentSkill.skill.label }}</label>
                                                <input class="form-control" value="{{ studentSkill.level|default('Non noté') }}" type="text" disabled>
                                            </div>
                                        {% endfor %}
                                    </div>
                                </div>
                            </div>
                        </div>
                        <!-- /.box-body -->
                    </div>
                    <!-- /.box -->
                {% endfor %}
            </div>
        </div>
    </div>
    <div class="col-md-12">
        <div class="col-md-12 sub-footer">
            {{ form_start(delete_form) }}
                <button class="btn-link text-red" onclick='return confirm("{{ 'label.delete.confirm_student'|trans }}")' type="submit">
                    {{ 'label.delete.student'|trans }}
                </button>
            {{ form_end(delete_form) }}
        </div>
    </div>
{% endblock %}

{% block javascripts %}
    <script type="text/javascript">
    </script>
{% endblock %}